### ISSUE TITLE
Exceptions for closed resources

### ISSUE THREAD

**Issue by azjezz** [revoltphp/event-loop#16]
Drivers result in different exceptions/errors making it harder for end-user to handle.

an example would be `EventLoop::onReadable`/`EventLoop::onWritable` throwing different exception/error depending on the driver in case the resource was closed at one point, instead, we should throw `ClosedResourceException`.

currently, I'm handling this case by catching `Throwable`, and checking if the resource was closed again: https://github.com/azjezz/psl/blob/2.0.x/src/Psl/Async/await_readable.php#L42-L54, but this method is not sufficient.

**Comment by kelunik** [comment]
This is currently indeed undefined behavior, applications and libraries are expected to clean up any registered callbacks before closing a resource locally.

The code you linked should not be throwing at all unless executed from main instead of from within a fiber.

**Comment by azjezz** [comment]
code sample:

```php
<?php

require 'vendor/autoload.php';

[$read, $_] = stream_socket_pair(STREAM_PF_UNIX, STREAM_SOCK_STREAM, STREAM_IPPROTO_IP);

stream_set_blocking($read, false);

Revolt\EventLoop::defer(function() use($read) {
    fclose($read);
});

Revolt\EventLoop::onReadable($read, static function ($watcher, $resource): void {
    Revolt\EventLoop::cancel($watcher);

    echo 'stream is ready';
});

$suspension = Revolt\EventLoop::createSuspension();
Revolt\EventLoop::delay(2, function() use($suspension) {
    $suspension->resume(null);
});

$suspension->suspend();
```

**Comment by kelunik** [comment]
Yeah, `Revolt\EventLoop::defer` closes the resource without cleaning up the read callback before. The whole event loop currently errors in that case.

**Comment by kelunik** [comment]
```php
public function testLocallyClosedResource(): void
{
    $this->start(function (Driver $loop): void {
        [$read] = \stream_socket_pair(STREAM_PF_UNIX, STREAM_SOCK_STREAM, STREAM_IPPROTO_IP);

        $loop->onReadable($read, static function (): void {});
        $loop->defer(function () use ($read): void {
            \fclose($read);
        });

        $loop->delay(1, fn () => self::fail('Expected exception to be thrown.'));
    });
}
```

- `stream_select` throws an exception
- `ext-event` ignores the bad file descriptor
- `ext-ev` raises a `EvLoop::run(): Libev error(9): Bad file descriptor` warning
- `ext-uv` ends with `signal 6: SIGABRT`

**Comment by azjezz** [comment]
@trowski mentioned that we can use assert to avoid having to check if every resource is closed in "production mode".

we can do this using something like:

```php
assert(
  (function() use($resource) {
    if (!is_resource($resource)) {
      throw new ResourceClosedException('resource has been closed');
    }

    return true;
  })()
);
```

**Comment by kelunik** [comment]
That's possible, yes, but I don't see another way to do it consistently without a larger performance penalty. We can still align the errors that _are_ detectable.

**Comment by kelunik** [comment]
See #20 for an initial implementation draft.

**Comment by kelunik** [comment]
I'll close this for now, as there isn't any way to do this in an efficient way.
