### ISSUE TITLE
Revolt w/Amphp or wait for new framework?

### ISSUE THREAD

**Issue by lakestonelabs** [revoltphp/event-loop#17]
After a while of studying and testing Amphp, I'm finally comfortable programing in Amp.  Then I learned about Revolt and its use of Fibers to simplify concurrent php programming.  The question/dilemma I have is which should I use now?  I would prefer to use Revolt so I don't have to do all of the yield/generator/call() mental juggling but I love the existing framework/libraries that Amp already provides.

So do I implement my own higher-level libs to use Revolt or is there a way I can use Revolt in conjunction with Amp or do I have to wait for another Revolt-based framework to be built?  Either way this is very exciting stuff.

**Comment by bwoebi** [comment]
Regarding Amp, there's a bunch vX (mostly v3 and v2) branches on the Amp repositories which already use Revolt.

**Comment by lakestonelabs** [comment]
Really!?  I'll have to check it out.  Thanks!  I understand that non-Revolt work will still be ongoing in Amp as it could take others many years to migrate to PHP 8.1 for Fibers.
