### ISSUE TITLE
PSR-3 LoggingDriver to trace all operations?

### ISSUE THREAD

**Issue by kelunik** [revoltphp/event-loop#21]
I have some weird issue in `amphp/http-client` that only happens with extension drivers where it doesn't trigger the readability callback and then eventually triggers a timeout delay callback, however when reading inside the timeout, there's still data to read.

I added some `print` based logging for debugging purposes, but I guess it could be helpful to have a logging decorator.

**Comment by WyriHaximus** [comment]
While I think this is a good idea to have support for. I also do think it's wise to make it configurable for which operations you want the logger. Especially given the legendary amount of events going through the event loop, plus if you're, like me, using a stream to write logs to `STDOUT` using a stream that goes through the event loop for scheduling you cause an amplification attack on your own event loop.

**Comment by kelunik** [comment]
Yeah, we need the logger to be passed in, so something like the magic env variable doesn't really work here. Maybe this should also be another debug package?

**Comment by WyriHaximus** [comment]
This is something @clue and I talked about as well. Which boils down to shouldn't all the tracing, metrics etc in a different debug/tracking/metrics package? Something along the lines of https://github.com/reactphp-inspector/event-loop/blob/master/src/LoopDecorator.php

**Comment by kelunik** [comment]
At least this should be in another packages, as we probably don't want any dependencies here.
