### ISSUE TITLE
Any idea of using this improve performance of previously existing PHP applications?

### ISSUE THREAD

**Issue by gkapoor121212** [revoltphp/event-loop#22]
Do we have any example of improving the performance of an already existing PHP framework or CMS? Are there any libraries that leverage event loop to enhance the performance?

**Comment by kelunik** [comment]
- All the new beta versions of https://github.com/amphp
 - https://github.com/azjezz/psl
 - All ReactPHP libraries via https://github.com/revoltphp/event-loop-adapter-react
