### ISSUE TITLE
rdkafka transport layering [Kafka <-> WebSocket]

### ISSUE THREAD

**Issue by Thurston00** [revoltphp/event-loop#28]
Would it be possible to use this library to maintain a connection to to a 3rd party API and an internal kafka broker using the [rdkafka extension](https://arnaud.le-blanc.net/php-rdkafka-doc/phpdoc/book.rdkafka.html)

We have a microservice design with many apps integrated with kafka, and we are working on rewriting our connector to a 3rd party service. We are a bit lost though on how we would be able to maintain a dual connection to both their 3rd party API (via websocket) and an internal kafka broker to send and received both ways.

**Comment by kelunik** [comment]
I'm not sure of the details of that extension, but here are the things you'll need:

 - You need some stream you can watch for IO events
 - You need non-blocking IO in the library
