### ISSUE TITLE
Bad file descriptor with "ev" driver when trying to listen on socket (Windows)

### ISSUE THREAD

**Issue by codercms** [revoltphp/event-loop#33]
This code:
```php
$socket = \Amp\Socket\listen('tcp://127.0.0.1:49000', null);
$socket->accept();
```

Throws this warning on Windows platform:
```
Warning: EvLoop::run(): Libev error(9): Bad file descriptor in ...\vendor\revolt\event-loop\src\EventLoop\Driver\EvDriver.php on line 164
```

php -v
```
PHP 8.1.1 (cli) (built: Dec 15 2021 10:36:13) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
```

php --ri ev
```
ev

Ev support => enabled
Debug support => disabled
Version => 1.1.6RC1
```

Package versions:
```
revolt/event-loop: v0.1.1
amphp/socket: v2.x-dev
```

**Comment by kelunik** [comment]
The event loop should never have a reference to a closed socket, so this is likely an issue in `amphp/socket` instead of `revolt/event-loop`. There's #20 to align the behavior for closed sockets, but it's not part of any release, yet.

I'll transfer the issue to `amphp/socket`.

**Comment by kelunik** [comment]
Nevermind, issue transfers are only possible within an organization, not cross-organization. :-(

**Comment by codercms** [comment]
@kelunik but socket isn't closed.

This code is working fine (if I switch to stream select driver):
```php
\Revolt\EventLoop::setDriver(new \Revolt\EventLoop\Driver\StreamSelectDriver());
$socket = \Amp\Socket\listen('tcp://127.0.0.1:49000', null);
$client = $socket->accept();

var_dump("Accepted connection {$client->getRemoteAddress()->toString()}");
```

```
string(35) "Accepted connection 127.0.0.1:64951"
```

**Comment by kelunik** [comment]
@codercms Can you still reproduce this with the latest versions?

**Comment by codercms** [comment]
@kelunik yes, but now I get different error:
EvLoop::run(): Libev error(10038): Unknown error in vendor\revolt\event-loop\src\EventLoop\Driver\EvDriver.php on line 155

Package versions:
```
revolt/event-loop: v0.2.5
amphp/socket: v2.x-dev
```

Some info about this error:
10038 (WSAENOTSOCK): Socket operation on nonsocket. An operation was attempted on something that is not a socket. Either the socket handle parameter did not reference a valid socket, or for select, a member of an fd_set was not valid.

**Comment by codercms** [comment]
@kelunik it seems like a bug inside the `ev` extension for Windows.
I found a build of `event` extension for Windows and PHP 8.1 - https://pecl.php.net/package/event/3.0.7RC1/windows
And with `event` extension everything works fine

**Comment by kelunik** [comment]
I'm closing this, see https://bitbucket.org/osmanov/pecl-ev/issues/36/windows-tcp-server-bug-warning-ev-run.

**Comment by codercms** [comment]
@kelunik maybe a little note should be added to the revolt docs? (to avoid using `ev` ext on Windows)
I think this note might save time for guys who will face the same problem with `ev` extension
