### ISSUE TITLE
Support idle watchers?

### ISSUE THREAD

**Issue by kelunik** [revoltphp/event-loop#4]
See https://github.com/amphp/amp/issues/214.

> _Idle watcher_ is a bad name, but I got that from http://docs.libuv.org/en/v1.x/design.html#the-i-o-loop. Basically watchers which are invoked on every loop iteration, but they shouldn't trigger an immediate new iteration IMO (like nested defers).

> https://github.com/kelunik/loop-block is one possible use case. Another would be moving signal handlers out of the event loop and into these idle handlers.

**Comment by WyriHaximus** [comment]
This could also hook into #5 and expose a metric for time between loop ticks

**Comment by kelunik** [comment]
The purpose would be exactly that, being able to hook into ticks to be able to calculate the metric without building it into the implementation itself.

A possible name could be `onTick`. One issue I see is that it won't be able to differentiate between stream_select blocking and a callback blocking.

**Comment by kelunik** [comment]
Rather than being able to measure ticks, it's probably more important to measure callbacks blocking.

**Comment by kelunik** [comment]
While libuv does have idle watchers, they're implemented in a way we can already emulate. Any active idle watchers result in a timeout of 0 while waiting for I/O, so this is very similar to scheduling a `defer` watcher inside itself every time until some condition is satisfied. Until then, the event loop will busy wait.
