### ISSUE TITLE
Add additional inspection tools

### ISSUE THREAD

**Issue by kelunik** [revoltphp/event-loop#5]
Currently there's `getInfo` to allow for some statistics, but I think it would be better to add further inspection tools for monitoring / debugging, e.g.

```
getCallbackIds(): array
getCallback(string): callable
isReferenced(string): bool
isEnabled(string): bool
getType(string): string // not sure which name fits here
```

This would probably also allow removing `getInfo()`.

**Comment by WyriHaximus** [comment]
Is there a way where we can make this optional? So that it only affects those who opt in to monitor their event loop?

**Comment by kelunik** [comment]
My thought was that these will be getters that can be used to monitor the internals of the event loop. If they are not called, they don't have any performance impact.

**Comment by kelunik** [comment]
See #62.
