### ISSUE TITLE
How to measure an event loop overhead?

### ISSUE THREAD

**Issue by codercms** [revoltphp/event-loop#51]
I'm writing a pure PHP equivalent of `libpq` that uses RevoltPHP v0.2.1 and Amp v3 (latest beta).
And after I implemented the basic things like sending queries/reading rows, I decided to profile the performance. 

And then I saw that the most time is spent on calling `Fiber::suspend`:
![image](https://user-images.githubusercontent.com/4526911/152958346-00140795-739a-433e-8554-94b570fab007.png)

If I understand correctly, `Fiber::suspend` time includes I/O wait time. 
But is there any way to see only I/O wait time?

When I tried to compare my performance results with the same bench, but using the `pgsql` PHP extension, it was almost twice as fast.

**Comment by kelunik** [comment]
The overall time is > 100% so you're likely using a benchmark tool that doesn't have proper support for fibers?

**Comment by codercms** [comment]
@kelunik I use xdebug 3.1.2 as profiler, doesn't it support fibers?

**Comment by kelunik** [comment]
That should be fine, Fibers are supported there as of 3.1.0.

**Comment by codercms** [comment]
@kelunik hmm, then I don't know what is going wrong with >100% overall time, btw I guess we can refer to "Own Time"
