### ISSUE TITLE
Mimic Octane::concurrently behavior

### ISSUE THREAD

**Issue by cayolblake** [revoltphp/event-loop#56]
Hello,

In `Laravel Octane` when using `Swoole` its possible to do something like the following.
```
	[ $recs1, $recs2 ] = Octane::concurrently( [
		fn() => $this->get_recs_a( $ids ),
		fn() => $this->get_recs_b( $ids )
	] );
```
What this will do is execute both functions `get_recs_a` and `get_recs_b` concurrently yet not returning unless both got executed and set their return values to `$recs1` and `$recs2`.

How to achieve similar behavior?

**Comment by kelunik** [comment]
Hey @cayolblake,

there are multiple ways to implement something like that, the easiest without any additional libraries is probably something like this:

```php
function concurrently(array $operations): array
{
	$result = [];
	$errors = [];

	$suspension = EventLoop::getSuspension();
	$remaining = \count($operations);

	foreach ($operations as $key => $operation) {
		EventLoop::queue(function () use ($key, $operation, $suspension, &$result, &$errors, &$pending) {
			try {
				$result[$key] = $operation();
			} catch (\Throwable $e) {
				$errors[$key] = $e;
			}

			if (--$pending === 0) {
				$suspension->resume();
			}
		});
	}

	$suspension->suspend();

	if ($errors) {
		throw new \Exception('Some operations failed');
	}

	return $result;
}
```

**Comment by cayolblake** [comment]
Hi @kelunik, 

Thank you so much for such function. Will test-drive it and reply back! 👍

**Comment by cayolblake** [comment]
Hi @kelunik 

So, I tried to execute this in a controller part of a https://github.com/walkor/webman/ framework project.

I got the following upon execution...

```
[2022-03-01 07:06:17] default.ERROR: Undefined property: Revolt\EventLoop\Internal\DriverSuspension::$fiber {"exception":"ErrorException: Undefined property: Revolt\\EventLoop\\Internal\\DriverSuspension::$fiber in vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php:109
Stack trace:
#0 vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php(109): {closure}()
#1 app/http/operations/articles/ArticlesOperations.php(232): Revolt\\EventLoop\\Internal\\DriverSuspension->suspend()
#2 app/http/operations/articles/ArticlesOperations.php(66): app\\http\\operations\\articles\\ArticlesOperations->concurrently()
...
... trace ommited ...
...
```

I run on PHP 8.1.3 and `revolt/event-loop` is at `v0.2.2`

**Comment by kelunik** [comment]
I guess you're hitting an error condition that has been fixed in https://github.com/revoltphp/event-loop/compare/v0.2.2...main, but not tagged, yet.

**Comment by cayolblake** [comment]
Okay, so I cloned master and replaced the current event-loop package I have and got the following different error.

```
[2022-03-01 07:42:18] default.ERROR: Event loop terminated without resuming the current suspension: {"exception":"Error: Event loop terminated without resuming the current suspension: in vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php:121
Stack trace:
#0 app/http/operations/articles/ArticlesOperations.php(232): Revolt\\EventLoop\\Internal\\DriverSuspension->suspend()
#1 app/http/operations/articles/ArticlesOperations.php(66): app\\http\\operations\\articles\\ArticlesOperations->concurrently()
...
... trace ommited ...
...
```

**Comment by cayolblake** [comment]
@kelunik any luck :)

**Comment by kelunik** [comment]
@cayolblake The error means you're suspending somewhere without registering an event to resume your suspension in the future. It's hard to tell where things go wrong without any code.

**Comment by cayolblake** [comment]
@kelunik 

Based on your code snippet, can you please clarify how to utilize this function?

A simple example may be? 🙄
