### ISSUE TITLE
Fiber stack protect failed

### ISSUE THREAD

**Issue by PNixx** [revoltphp/event-loop#65]
I catch error in my production server in callback method `set_exception_handler(***)`:

```
Fiber stack protect failed: mprotect failed: Cannot allocate memory (12), /project/vendor/revolt/event-loop/src/EventLoop/Internal/AbstractDriver.php:495
```

In `php.ini`:

```ini
; Maximum amount of memory a script may consume
; https://php.net/memory-limit
memory_limit = -1
```

Available memory in server 230Gb.

**Comment by bwoebi** [comment]
There exists another sysctl parameter, `vm.max_map_count`, which limits the maximum number of individual fiber allocations. Could you please check whether increasing that helps?

**Comment by PNixx** [comment]
I increased the value in the system from 65530 to 262144. I will monitor the server logs for a couple of days and will return with feedback.

**Comment by PNixx** [comment]
After increase I catch similar errors `Failed to open stream: Too many open files` with any methods: `require_once, file_put_contents` and more. So far I can not say 100% whether it is connected with these changes or not.

**Comment by PNixx** [comment]
Yes, this is confirmed. I'll try to reduce the value to 131060.

**Comment by PNixx** [comment]
Now I catch `Fiber stack protect failed: mprotect failed: Cannot allocate memory`. Any ideas?

**Comment by bwoebi** [comment]
This is a different issue - too many open files refers to `ulimit -n` (or `fs.file-max`).

**Comment by PNixx** [comment]
```
$ ulimit -n
65000
$ cat /proc/sys/fs/file-max
9223372036854775807
```
Our system administrator increases these parameters when installing and configuring the system.

**Comment by kelunik** [comment]
If you reach the limit and don't want to increase it further, you'll need to have a look which files are open and whether they should be open at that point.
