### ISSUE TITLE
A problem in Windows: `StreamSelectDriver::$streamSelectErrorHandler` 

### ISSUE THREAD

**Issue by tianyiw2013** [revoltphp/event-loop#67]
## Issue
In Windows, when I type ctrl+c, an exception is thrown. 
There are no problems under the Linux system.
I don't know why. Please help me to see if this is a bug?
Please look at my code. I used the error suppressor to call mkdir, which should not throw an exception.

https://github.com/revoltphp/event-loop/blob/81dd825a0a7fa7a39cae25ef731bb944f3e18295/src/EventLoop/Driver/StreamSelectDriver.php#L54
I think a judgment error report can be added to `StreamSelectDriver::$streamSelectErrorHandler`
`if ((error_reporting() & $errno) == 0)return;`

I can solve this problem in my code, but I don't know why `register_shutdown_function` executed in the event loop.

My English is very poor. Please look at the code. Thank you

## PHP code
```php
<?php

require __DIR__ . '/vendor/autoload.php';

use Revolt\EventLoop;

$server = \stream_socket_server('tcp://0.0.0.0:8080');
\stream_set_blocking($server, false);

EventLoop::onReadable($server, fn () => null);

\register_shutdown_function(function () {
    @mkdir(__FILE__); // I deliberately made an error, but I masked it through the error suppressor.
});

if (DIRECTORY_SEPARATOR === '\\') {
    sapi_windows_set_ctrl_handler(function () {
        echo "ctrl+c." . PHP_EOL;
        exit;
    });
} else {
    if (defined('\SIGINT')) {
        EventLoop::onSignal(\SIGINT, function () {
            echo "ctrl+c." . PHP_EOL;
            exit;
        });
    }
}

EventLoop::repeat(1, fn () => null);

echo "started." . PHP_EOL;

EventLoop::run();

```

## Windows system threw an exception 
- Windows 11
- PHP 8.2.0RC5
```text
F:\revolt>php test.php
started.
ctrl+c.
PHP Fatal error:  Uncaught Exception: mkdir(): File exists in F:\revolt\vendor\revolt\event-loop\src\EventLoop\Driver\StreamSelectDriver.php:77
Stack trace:
#0 [internal function]: Revolt\EventLoop\Driver\StreamSelectDriver->Revolt\EventLoop\Driver\{closure}(2, 'mkdir(): File e...', 'F:\\revolt\\test....', 14)
#1 F:\revolt\test.php(14): mkdir('F:\\revolt\\test....')
#2 [internal function]: {closure}()
#3 {main}
  thrown in F:\revolt\vendor\revolt\event-loop\src\EventLoop\Driver\StreamSelectDriver.php on line 77
```

## Linux system is OK
```text
tianyiw@TIANYIW-HOME-PC:~/revolt$ php test.php
started.
^Cctrl+c.
```

**Comment by kelunik** [comment]
That error handler should only be active during the stream_select call and not in any of your code. I guess the issue is that exit within the sapi_windows_set_ctrl_handler, which probably avoids executing the finally handler there?

**Comment by kelunik** [comment]
My suggestion is scheduling a callback in the event loop instead of directly running code inside `sapi_windows_set_ctrl_handler` like this:

```php
sapi_windows_set_ctrl_handler(function () {
    EventLoop::queue(function () {
        echo "ctrl+c." . PHP_EOL;
        exit;
    });
});
```

**Comment by tianyiw2013** [comment]
Good idea! Solve the problem!
Thank you.

If there is no performance loss, I think you can consider whether to merge the PR #68
