### ISSUE TITLE
Have a question in Suspension

### ISSUE THREAD

**Issue by xjaja** [revoltphp/event-loop#73]
I see a property

https://github.com/revoltphp/event-loop/blob/6eca0517b05fed5e51dc0d2edb6cf2cdbba436b7/src/EventLoop/Internal/DriverSuspension.php#L17

It add in #52 to use  `resume` `throw`.

But the commit [0ea6f6](https://github.com/revoltphp/event-loop/commit/0ea6f60ac86e3417c3c4b9b4cef9dd4b4f0f79f9)  `resume` `throw` remove the property.

Does it need to be cleaned up or does it have any function.

I think it cause leak, related https://github.com/revoltphp/event-loop/pull/52#issuecomment-1042396714.

**Comment by kelunik** [comment]
Somebody has to keep a reference to the fiber, so it's not garbage collected, no?

**Comment by xjaja** [comment]
Thanks
