### ISSUE TITLE
Segfault question

### ISSUE THREAD

**Issue by veewee** [revoltphp/event-loop#80]
I'm getting some segfaults reported on older PHP versions (< 8.1.17 and <8.2.4) in our GrumPHP project.
Would it make sense to add a conflict section in the composer file of this package so that people know there something wrong with their setup?

It's a PHP bug but it make usage of fibers rather unstable: 

* [GH-10496](https://github.com/php/php-src/issues/10496) (segfault when garbage collector is invoked inside of fiber).

I can always add it to my project, but it might make more sense to add it here so that other projects can benifit from this as well.

**Comment by kelunik** [comment]
We had this on our plan, but forgot about it. A conflict rule is probably not the right way, as people on broken versions would just install an older version then without noticing. We should probably add a runtime check instead.

**Comment by kelunik** [comment]
See #85.
