### ISSUE TITLE
Consider documenting a security policy

### ISSUE THREAD

**Issue by Kingdutch** [revoltphp/event-loop#87]
The [Drupal framework is looking to adopt Revolt as its event loop](https://www.drupal.org/project/drupal/issues/3394423). Since this would become a very integral part of Drupal (with some existing systems already moving to async), one of the evaluation criteria is that the package has a security policy that outlines how to properly report security issues.

From one of Drupal's security team members on the issue discussing Revolt's adoption:
> Can we ask the maintainers if they are willing to publish a security policy? Given that this is a low level runtime dependency it seems quite important that if there is a security issue the maintainers are prepared to fix it within a reasonable timescale.

Would it be possible to clarify Revolt's security policy and document it in a `SECURITY.md` file so it shows up in GitHub's security tab? This can also help other larger frameworks in adopting Revolt :)

**Comment by kelunik** [comment]
Good point, it's indeed missing here. I've just enabled private vulnerability reporting and added a SECURITY.md file.
