### ISSUE TITLE
It is hoped to unify the execution sequence of signal events

### ISSUE THREAD

**Issue by cclilshy** [revoltphp/event-loop#94]
Sorry, the translation of the issue may not be very accurate

They should have a standard execution order: the processor registered later executes in the front, so the framework has more control over resources; Even if I do not take my advice, I hope he can unify a fixed order, as it seems that he has a different order of signal processor registration between libevent and ev

```php
EventLoop::onSignal(SIGINT, function () {
    echo 'handle 1.' . PHP_EOL;
    exit;
    // from framework, The first registration should be performed at the end
});

EventLoop::onSignal(SIGINT, function () {
    echo 'handle 2.' . PHP_EOL;
    // from developer, After the registration should be executed first
});
```

**Comment by kelunik** [comment]
Why should the second callback be executed first?

**Comment by cclilshy** [comment]
> 为什么要先执行第二个回调呢？

I might register a signal handler for resource cleanup before everything is ready, and also allow developers to register their own signal handlers. If the user's signal processor occurs after my resource reclamation, it may affect the user's operation; The signal-processor I signed up for happens to ensure that at the end, other developers can leave the problem to the framework itself without worrying too much about resource cleanup, of course possibly considering that the user will execute exit, but if he does, hopefully he knows what will happen

**Comment by kelunik** [comment]
The callback invocation order is explicitly defined as being undefined, so any order can happen:

https://github.com/revoltphp/event-loop/blob/358572ca31647df7dbe930f13c8567136beffa33/src/EventLoop.php#L199

Generally, I'd recommend not registering signal handlers in library code, but rather offering the user of the library to call some shutdown / signal handling logic, e.g. via a dedicated method.

That way the user can register the signal callback and there will be only one such handler.

**Comment by cclilshy** [comment]
Well, maybe I should reassess. Thank you
